### ISSUE TITLE
[Bug]: Upload meta bake definition an artifact with this name already exists

### ISSUE THREAD

**Issue by sinlov** [bridgewwater/template-docker-runtime-alpine#22]
### Component

CI/CD

### Describe the bug

```log
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

### System Info

```shell
any
```

### Validations

- [X] Read the [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_DOC/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](../issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already.
